server.port=8000
spring.application.name=user
#Database & Migrations
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:postgresql://localhost:5432/database
spring.datasource.password=password
spring.datasource.username=user
spring.flyway.password=password
spring.flyway.user=user
spring.flyway.url=jdbc:postgresql://localhost:5432/database
logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.session=DEBUG