server.port=8000
spring.application.name=user
#Database
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:postgresql://localhost:5432/database
spring.datasource.password=password
spring.datasource.username=user
#Migrations
spring.flyway.password=password
spring.flyway.user=user
spring.flyway.url=jdbc:postgresql://localhost:5432/database
#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379