CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100)       NOT NULL
);


CREATE TABLE IF NOT EXISTS roles
(
    id   BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    role varchar(50) UNIQUE NOT NULL
);


CREATE TABLE IF NOT EXISTS user_role
(
    id      BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT,
    role_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles (id)
);
ALTER TABLE user_role
    ADD CONSTRAINT unique_user_id_and_role_id UNIQUE (user_id, role_id);