worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 45;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml+rss text/javascript;
    gzip_min_length 256;

    client_max_body_size 30M;

    server {
        listen 80;

        location ~ /\. {
            deny all;
            access_log off;
            log_not_found off;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;

            client_max_body_size 30M;
        }
    }
}