services:
  backend:
    container_name: backend
    image: romilmasnaviev/backend-cloudstorage
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx256m -Xms256m"
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - redis
      - postgres
    networks:
      - cloud-storage-network
    restart: always

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - cloud-storage-network
    restart: always

  redis:
    image: redis:8-alpine
    container_name: redis
    volumes:
      - rs_data:/data
    networks:
      - cloud-storage-network
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data/
    networks:
      - cloud-storage-network
    restart: always

  frontend:
    container_name: frontend
    image: romilmasnaviev/frontend-cloudstorage
    depends_on:
      - backend
    networks:
      - cloud-storage-network
    restart: always

  nginx:
    container_name: main-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      # Проверь путь! Если ты в папке infra, то путь должен быть ./nginx.conf
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - backend
      - frontend
    networks:
      - cloud-storage-network
    restart: always

networks:
  cloud-storage-network:

volumes:
  pg_data:
  rs_data:
  minio-data: