version: '3.8'
# Only Postgres, Redis, Minio. for user app use application-local.properties
services:

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - cloud-storage-network

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - rs_data:/data
    networks:
      - cloud-storage-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data/
    networks:
      - cloud-storage-network

networks:
  cloud-storage-network:

volumes:
  pg_data:
  rs_data:
  minio-data: